### ISSUE TITLE
add option to use nonlocal database

### ISSUE THREAD

**Issue by lauriholmas** [lotheac/bcproxy#1]
Hello,
would be nice to have an easily configurable option to use nonlocal database. ( At my shell machine the admins are too lazy to install psql, going to use a db from heroku or something). 

need to give host, user, pass probably.

**Comment by lotheac** [comment]
as discussed in-game, an ssh tunnel will probably solve your immediate need here. sqlite support has also been suggested separately but nobody's written it yet.

closing this based on our talk.
